// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qccbjwbbytmnbsvdcxea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjY2Jqd2JieXRtbmJzdmRjeGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDM0MjcsImV4cCI6MjA3MTI3OTQyN30.w3q1EDsSbEpuevAYhNZ6uMGLcmkyozoLOSc-UUxaVeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});